version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: apache-host
    ports:
    - '8080:80'
  script:
    container_name: script-docker
    build: .
    volumes:
      - ./logs:/httpd/logs

